swf_1:
  path:       /swf/cross.swf
  tag:        test_swf
  width :     100%
  height:     100%
  flash_ver:  10.0.0
  flashvars:  
    base: local.mondep.com 
  params:     
    wmode: transparent
  attributes: 
    id: test 
  
  
swf_2:
  path:      /swf/cross.swf
  tag:       test_swf_2
  width:     300
  height:    100
  flash_ver: 10.0.0